FROM digrouz/alpine-s6:latest
LABEL maintainer "DI GREGORIO Nicolas <nicolas.digregorio@gmail.com>"

ARG JOAL_VERSION='2.1.33'

### Environment variables
ENV LANG='en_US.UTF-8' \
    LANGUAGE='en_US.UTF-8' \
    JOAL_VERSION="${JOAL_VERSION}"

# Copy config files
COPY root/ /

RUN set -x && \
    apk --no-cache upgrade && \
    apk add --no-cache --virtual=run-deps \
      ca-certificates \
      openjdk11 \
    && \
    mkdir /joal /config && \
    wget https://github.com/anthonyraymond/joal/releases/download/${JOAL_VERSION}/joal.tar.gz -O /tmp/joal.tar.gz && \
    tar xzf /tmp/joal.tar.gz -C /joal && \
    mv /joal/jack-of-all-trades-${JOAL_VERSION}.jar /joal/joal.jar && \
    chown -R appuser /joal /config && \
    rm -rf /tmp/* \
           /var/cache/apk/*  \
           /var/tmp/*

### Volume
VOLUME ["/config"]

### Expose ports
EXPOSE 1234