name: dockerhub-workflow

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push tag latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/joal:latest
      -
        name: Build and push tag alpine
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile_alpine
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/joal:alpine
